name: Stale issues & PRs

on:
  schedule:
    - cron: '0 5 * * *'  # daily
  workflow_dispatch:

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: chodeus/chodeus-ops/.github/workflows/stale-issues.yml@main
